### ISSUE TITLE
P.127 Yaml 파일

### ISSUE THREAD

**Issue by Kyoungtaek** [bjpublic/aws_lambda#1]
CloudFormation을 위한 Yaml파일에 문제가 있는 것 같습니다. 실슬 진행이 막혔습니다.
git에 실습에 사용된 yml파일을 첨부해주시면 감사하겠습니다.

**Comment by KimMinJunDev** [comment]
안녕하세요? 아래 소스입니다.
파일명.yml 로 저장해서 사용해보세요. 

출판사에 전달드리긴했는데 아래 제가 따로 올려두었습니다.

https://github.com/KimMinJunDev/aws_lambda_book_2020/blob/main/cloudformation.yml

감사합니다.




AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Lambda Test
Resources:
  CloudFormationLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: !Join
          - |+
          - - import json
            - 'def lambda_handler(event,context):'
            - '    return ''Lambda Test'''
      Handler: index.lambda_handler
      Role: !GetAtt LambdaIAMRole.Arn
      Runtime: python3.7
      Timeout: 5

  LambdaIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
